---

- name: Verificação do sudo
  fail:
    msg: 
      - Essa task foi criada para trocar chaves usando um login não root
      - Desative o ansible_become para rodar essa task
  when: ansible_become == 'yes' or not ansible_become is defined

- name: Verificar se o sshpass está instalado
  stat:
     path: /usr/bin/sshpass
  register: stat_sshpass

- name: Resultado da verificação do sshpass
  fail:
    msg: 
      - Falha ao encontrar o /usr/bin/sshpass no {{ ansible_hostname }}
      - Instale o sshpass e rode a task novamente
  when: not stat_sshpass.stat.exists

- name: Geração da chave no host {{ ansible_hostname }}
  openssh_keypair:
    path: ~/.ssh/id_rsa
    size: 2048
    force: no

- name: Criação de um arquivo temporário com a senha do ssh
  shell:
    cmd: echo {{ ansible_ssh_pass }} > ~/.ssh/pass.tmp

- name: Instalação da chave nos servidores alvos
  shell:
    cmd: sshpass -f ~/.ssh/pass.tmp ssh-copy-id -p {{ ansible_ssh_port }} -i ~/.ssh/id_rsa {{ ansible_ssh_user }}@{{ item }}
  loop:  "{{ target_servers }}"
  register: command_result
  failed_when:
    - "'FAIL' in command_result.stderr"
       
- name: Remoção do arquivo temporário
  file:
    name: ~/.ssh/pass.tmp
    state: absent
...
